#!/bin/sh

set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
echo "--- RUNNING CTAGS ---"
git ls-files | \
      ctags --tag-relative --extra=+f -L - -f"$dir/$$.tags" --languages=-sql
      mv "$dir/$$.tags" "$dir/tags"
