#!/usr/bin/env ruby

message_file = ARGV[0]
original_message = File.read(message_file)

# Don't do anything if the commit already has a jira link
unless original_message =~ /technekes\.atlassian\.net/
  current_branch = `git rev-parse --abbrev-ref HEAD 2>/dev/null`.chomp
  match = current_branch.scan(/[a-z]+-\d+/i).first

  if match
    jira_ticket = match.upcase
    jira_link   = "[#{jira_ticket}](https://technekes.atlassian.net/browse/#{jira_ticket})"
    new_message = "\n\n#{jira_link}"

    puts ARGV.inspect
    puts original_message

    content = if ARGV[1] == 'message' # a commit with -m
                original_message + new_message
              else
                new_message + original_message
              end

    File.write(message_file, content)
  end
end
