brew "zsh"
brew "mas"
brew "dockutil"
brew "fasd"
brew "reattach-to-user-namespace"
brew "fzf"
brew "tmpreaper"
brew "the_silver_searcher"
brew "heroku-toolbelt"
brew "hub"
brew "tmux"
brew "go"
brew "googler"
brew "docker"
brew "docker-compose"
brew "docker-machine"
brew "automake"
brew "jq"

brew "redis", restart_service: true
brew "imagemagick"
brew "postgres"
brew "git"
brew "git-extras"

cask "dropbox"
cask "postman"
cask "spotify"
cask "caffeine"
cask "iterm2"
cask "firefox"
cask "google-chrome"
cask "harvest"
cask "virtualbox"
cask "slack"
cask "github-desktop"
cask "screenhero"
cask "flux"

# Low priority stuff
brew "keybase"
brew "ack"
brew "pandoc"
brew "ghi"
brew "diff-so-fancy"
