tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'homebrew/versions'
brew 'cask'

# Essentials
brew 'git'
brew 'hub'
tap 'universal-ctags/universal-ctags'

brew 'autoconf'
brew 'automake'

brew 'browser'
brew 'diff-so-fancy'
brew 'docker'
brew 'docker-machine'
brew 'docker-compose'
brew 'dockutil'
brew 'fasd'
brew 'tmpreaper'
brew 'tree'
brew 'zsh'
brew 'git-extras'
brew 'tmux'
brew 'rbenv-default-gems'
brew 'rbenv-ctags'

brew 'openssl'
brew 'pinentry'
brew 'gpg-agent'
brew 'gnupg2'
brew 'pinentry-mac'

brew 'go'
brew 'googler'

brew 'heroku'
brew 'htop'
brew 'jq'
brew 'keybase'

brew 'mas'
brew 'node'

brew 'pandoc'
brew 'phantomjs'
brew 'postgresql', restart_service: true

brew 'ruby-build'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'redis', restart_service: true
brew 'rename'
brew 'shellcheck'
brew 'source-highlight'
brew 'the_silver_searcher'
brew 'homebrew/versions/redis28'
cask 'caffeine'
cask 'dropbox'
cask 'filezilla'
cask 'firefox'
cask 'flux'
cask 'font-dejavu-sans'
cask 'font-fira-mono-for-powerline'
cask 'font-inconsolata'
cask 'github-desktop'
cask 'google-chrome'
cask 'harvest'
cask 'iterm2'
cask 'postman'
cask 'screenhero'
cask 'slack'
cask 'spotify'
cask 'virtualbox'
