#!/bin/sh

alias setup="~/.files/script/setup"

alias vim="nvim"
alias vi="nvim"
alias v="nvim"
alias vimrc="vim ~/.vimrc"

alias gppf="git push --force-with-lease"
# "Git Nuke" deletes everything but current branch
alias gnuke="git branch | grep -v '^*' | xargs git branch -D "
alias gca="git commit --amend --no-edit"

gppr(){
  git fetch --prune && git branch -r | \
    awk '{print $1}' | \
    egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | \
    awk '{print $1}' | xargs git branch -D
}
alias gs="git status"

alias be="bundle exec"

gclone(){ git clone git@github.com:$1/$2.git; cd $(basename $2); }

