#!/bin/sh

alias setup="~/.files/script/setup"

# fasd same behavior as autojump
alias j='fasd_cd -d'

alias nalias="vim ~/.files/lib/aliases"

alias notes="~/Desktop/notes"

alias vim="nvim"
alias vi="nvim"
alias v="nvim"
alias vimrc="vim ~/.vimrc"

alias git="hub"
alias gpr="git pull-request"
alias gl="git log --decorate --graph --oneline"
alias gh="log --pretty=format:\"%h %ad | %s%d [%an]\" --graph --date=short"
alias gpl="git pull"
alias gp="git push"
alias gs='git status -sb'
alias gppf="git push --force-with-lease"  #  "pretty please force push"
alias gc="git commit"
alias gca="git commit --amend --no-edit"
alias gco="git checkout"
alias gb="git branch"
alias gd="git diff"

# "Git Nuke" deletes everything but current branch
alias gnuke="git branch | grep -v '^*' | xargs git branch -D "

gppr(){
  git fetch --prune && git branch -r | \
    awk '{print $1}' | \
    egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | \
    awk '{print $1}' | xargs git branch -D
}

alias be="bundle exec"

gclone(){ git clone git@github.com:$1/$2.git; cd $(basename $2); }

todo(){ ghi open -m "${*}" --claim }

work(){
  if [ ! $(tmux ls | grep work | cut -c1-4) &> /dev/null ]; then
    tmux new -s work
  else
    tmux attach -t work
  fi
}
