#!/bin/bash

link_safe() {
  SOURCE=$1
  SOURCE_DIR="$PWD"
  SOURCE_PATH="$SOURCE_DIR/$SOURCE"

  DEFAULT_DESTINATION="$HOME/$(basename $SOURCE)"
  DESTINATION_PATH=${2:-$DEFAULT_DESTINATION}

  if [[ ! -f "$SOURCE_PATH" ]] || [[ $(ls -l "$SOURCE_PATH" | awk '{print $11}') != "$DESTINATION_PATH" ]]; then
    echo "Linking $DESTINATION_PATH to $SOURCE_PATH"
    rm -f "$DESTINATION_PATH"
    ln -s "$SOURCE_PATH" "$DESTINATION_PATH" 
  fi
}

mkdir_safe() {
  if [[ ! -d "$1" ]]; then
    echo "Creating $1 directory"
    mkdir -p "$1"
  fi
}
