#!/bin/sh

export DOTFILES_ROOT="$HOME/.files"

# Preferred editor for local and remote sessions
 if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
 else
   export EDITOR='nvim'
 fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# set up rbenv
# eval "$(rbenv init -)"
export PATH=$HOME/.rbenv/bin:$PATH
eval "$(rbenv init -)"

export GOPATH=~/dev/go
export PATH="/usr/local/bin:$PATH"

