#!/bin/sh

export DOTFILES_ROOT="$HOME/.files"

# Preferred editor for local and remote sessions
 if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
 else
   export EDITOR='nvim'
 fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# set up rbenv
export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"

export GOPATH=~/dev/go
export PATH="/usr/local/bin:$PATH"

export ZSH=$HOME/.oh-my-zsh
export ZSH_THEME="honukai"
export DISABLE_UPDATE_PROMPT="true"
export COMPLETION_WAITING_DOTS="true"
