#!/bin/sh

export DOTFILES_ROOT="$HOME/.files"

# Preferred editor for local and remote sessions
 if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
 elif type nvim &> /dev/null; then
   export EDITOR='nvim'
 else
   export EDITOR='vim'
 fi

export HOMEBREW_GITHUB_API_TOKEN=$(cat ~/.secrets/github-token)

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# set up rbenv
export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:/usr/local/bin:$PATH"

export GOPATH=~/dev/go

export ZSH=$HOME/.oh-my-zsh
export ZSH_THEME="honukai"
export DISABLE_UPDATE_PROMPT="true"
export COMPLETION_WAITING_DOTS="true"
