#!/bin/sh

# Stops and removes all running docker containers
dnuke() {
  if [[ "$(docker ps -aq)" > /dev/null ]] ; then
    docker stop "$(docker ps -a -q)" && docker rm "$(docker ps -a -q)"
  fi
}


# Used for https://github.com/technekes/nib
alias nib='
docker run \
  -it \
  --rm \
  -v $(pwd):$(pwd) \
  -w $(pwd) \
  -v $HOME/.docker:/root/.docker:ro \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -e "DOCKER_HOST_URL=$DOCKER_HOST" \
  technekes/nib'

alias pry='
docker run \
  -it \
  --rm \
  -v $(pwd):$(pwd) \
  -w $(pwd) \
  -v $HOME/.docker:/root/.docker:ro \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -e "DOCKER_HOST_URL=$DOCKER_HOST" \
  colstrom/pry'
