#!/bin/sh

alias dot="cd $DOTFILES_ROOT"
alias setup="$DOTFILES_ROOT/script/setup"
alias nalias="$EDITOR ~/.files/lib/aliases"

# List all setups
setups() {
  for setup in ${DOTFILES_ROOT}/script/setups/*; do
    if [ -f "$setup" ]; then echo $(basename "$setup"); fi
  done
}

