#!/bin/sh

alias dotfiles="cd $DOTFILES_ROOT"
alias setup="$DOTFILES_ROOT/script/setup"
alias nalias="$EDITOR ~/.files/lib/aliases"
alias zshrc="$EDITOR ~/.zshrc"
alias rz="source ~/.zshrc"

# List all setups
setups() {
  for setup in ${DOTFILES_ROOT}/script/setups/*; do
    if [ -f "$setup" ]; then basename "$setup"; fi
  done
}

up() {
  ${DOTFILES_ROOT}/script/update
}

