#!/bin/sh

# Fuzzy finder to open files from command line.
# Uses $EDITOR if defined, otherwise vim.
#
# Think "Fuzzy Edit"
fe() {
  local files
  IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --exit-0))
  [[ -n "$files" ]] && ${EDITOR:-vim} "${files[@]}"
}

