#!/bin/sh

alias g="git"
alias gaa="git add --all"
alias gb="git branch"
alias gc="git commit --verbose"
alias gca="git commit --amend --no-edit"
alias gcb="git checkout -b"
alias gd="git diff"
alias git="hub"
alias gh="hub browse"
alias gl="git log --decorate --graph --oneline"
alias gp="git push"
alias gpl="git pull"
alias gppf="git push --force-with-lease"  #  "pretty please force push"
alias gpr="git pull-request"
alias gra="git rebase --abort"
alias grc="git rebase --continue"
alias gs='git status -sb'
alias gsh="git stash"
alias gsha="git stash apply"

alias fixup="gaa && gca && gppf"

alias qa="git checkout qa"
alias dev="git checkout development"
alias master="git checkout master"

alias grm="git rebase master"
alias grim="git rebase -i master"

# "Git Nuke" deletes everything but current branch
alias gnuke="git branch | grep -v '^*' | xargs git branch -D "

# This is broken for right now. :(
# gppr(){
#   git fetch --prune && git branch -r | \
#     awk '{print $1}' | \
#     egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | \
#     awk '{print $1}' | xargs git branch -D
# }

alias contributors=" git --no-pager log -s --format='%ae' | sort -u "

unalias gco 2>/dev/null
gco() { git checkout $1 2> /dev/null || git checkout -b $1; }

gclone() { git clone git@github.com:$1/$2.git && cd $(basename $2); }

