#!/bin/sh

alias g="git"
alias git="hub"
alias gpr="git pull-request"
alias gl="git log --decorate --graph --oneline"
alias gh="log --pretty=format:\"%h %ad | %s%d [%an]\" --graph --date=short"
alias gpl="git pull"
alias gp="git push"
alias gs='git status -sb'
alias gppf="git push --force-with-lease"  #  "pretty please force push"
alias gc="git commit"
alias gca="git commit --amend --no-edit"
alias gco="git checkout"
alias gb="git branch"
alias gd="git diff"
alias grc="git rebase --continue"
alias gra="git rebase --abort"
alias gsh="git stash"
alias gsha="git stash apply"

# "Git Nuke" deletes everything but current branch
alias gnuke="git branch | grep -v '^*' | xargs git branch -D "

# This is broken for right now. :(
# gppr(){
#   git fetch --prune && git branch -r | \
#     awk '{print $1}' | \
#     egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | \
#     awk '{print $1}' | xargs git branch -D
# }


gclone() { git clone git@github.com:$1/$2.git && cd $(basename $2); }

todo() { ghi open -m "${*}" --claim }

