#!/bin/sh
#
# Opens/creates a tmux session.
# If no parameter is given, an existing session will be loaded if available
#
# Usage t [session_name]

t(){
  local target=$1
  if [[ "$target" == "ls" ]]; then
    tmux ls 2&>/dev/null || echo "No sessions"
  elif [ ! $(tmux ls | grep "$target" | cut -c1-4) &> /dev/null ]; then
    tmux new -s "$target"
  else
    tmux attach -t "$target"
  fi
}

alias tc="$EDITOR ~/.tmux.conf"
