#!/usr/bin/env ruby

require "fileutils"
require "date"

FOOD_LOG_PATH="#{ENV['HOME']}/Desktop/food-log.txt"

def timestamp
  Time.now.strftime "%d %B %Y at %H:%M"
end

def foodstamp(meal, *args)
  food = args.join(" ")
 "#{timestamp} \t- #{meal} - \t#{food}\n"
end

def new_day?(some_statement)
  statement_date(some_statement) < Date.today
end

def statement_date(str)
  date_str = str.split.first(3).join(" ")
  DateTime.strptime(date_str, "%d %B %Y")
end

def handle_pretty_line(some_file_path, file_handler)
  first_line = File.open(some_file_path, &:readline)
  file_handler.puts "-" * 100 if new_day?(first_line)
end

def update_log(meal, *args)
  statement = foodstamp(meal, args)

  unless File.exists? FOOD_LOG_PATH
    FileUtils.touch FOOD_LOG_PATH
  end

  original_file = FOOD_LOG_PATH
  new_file = FOOD_LOG_PATH + ".tmp"

  File.open(new_file, 'w') do |fo|
    STDOUT.print "Adding '#{statement.strip.delete("\t")}' to log... "
    fo.puts statement
    handle_pretty_line(original_file, fo)

    File.foreach(original_file) do |li|
      fo.puts li
    end
  end

  File.rename(new_file, FOOD_LOG_PATH)
  STDOUT.print "✓\n"
end

update_log(ARGV.shift, ARGV)

