#!/usr/bin/env bash
#
# bootstrap installs things.

set -e

# Bootstrap dotfiles
if [[ ! -d "$HOME/.files" ]]; then
  git clone https://github.com/binarymason/dotfiles ~/.files
fi

source "$HOME/.files/lib/globals"
source "$DOTFILES_ROOT/lib/functions"

setups=($(ls "$DOTFILES_ROOT/script/setup/"))

for setup in "${setups[@]}"; do
  script/title "Setting up $setup"
  "script/setup/$setup"
done

script/title "Bootstrap complete."
