#!/bin/sh
#
# Starts a RescueTime focus session of 25 minutes

source "$HOME/.files/script/init"
source "$HOME/.secrets/ifttt-maker"
source "$HOME/.secrets/slack-token"

EVENT="rescue_time_focus_start"
info "Firing $EVENT blink(1) event to IFTT"
curl -X POST https://maker.ifttt.com/trigger/${EVENT}/with/key/${IFTTT_MAKER_KEY} &>/dev/null && ok

SLACK_PRESENCE=away
info "Changing slack presence to $SLACK_PRESENCE"
setpresenceurl="https://slack.com/api/users.setPresence?token=$SLACK_TOKEN&presence=$SLACK_PRESENCE&pretty=1"
curl -X POST "$setpresenceurl" &>/dev/null && ok

DO_NOT_DISTURB_MINUTES=25
info "Changing slack to do not disturb for $DO_NOT_DISTURB_MINUTES minutes"
DNDURL="https://slack.com/api/dnd.setSnooze?token=$SLACK_TOKEN&num_minutes=$DO_NOT_DISTURB_MINUTES&pretty=1"
curl -X POST "$DNDURL" &>/dev/null && ok

