#!/bin/sh
#
# Outputs a shortened goo.gl link.
# If no argument is given, it defaults to what is on OSX clipboard
#
# Usage: glink [URL]
#
# Dependencies: jq (see https://stedolan.github.io/jq/)

source "$HOME/.secrets/google-link-shortener"

longUrl=${1:-$(pbpaste)}

shortUrl=$(
curl -s https://www.googleapis.com/urlshortener/v1/url\?key\=${GLINK_API_KEY} \
  -H 'Content-Type: application/json' \
  -d "{\"longUrl\": \"$longUrl\"}" | jq -r '.id'
)

echo "$shortUrl" | pbcopy
echo "$shortUrl (copied to clipboard)"

