#!/bin/sh

source "$HOME/.files/lib/globals"
source "$DOTFILES_ROOT/lib/functions"

if [ ! $(command -v brew) &> /dev/null ]; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

