#!/bin/sh
#
# Setup stuff. Runs all setups unless given an argument
# Usage is setup [something specific]

set -e

target=$1

echo "Starting setup... $target"

# Bootstrap dotfiles if needed
if [[ ! -d "$HOME/.files" ]]; then
  git clone https://github.com/binarymason/dotfiles ~/.files
fi

# Source dotfiles init stuff
source "$HOME/.files/script/init"

if [ ! -z "$target" ]; then
  "$DOTFILES_ROOT"/script/setups/"$target"
  echo ""
  echo "✓"
else
  for setup in "$DOTFILES_ROOT"/script/setups/*; do
    # Only execute files not directories
    if [ -f "$setup" ]; then
      "$DOTFILES_ROOT"/script/title "Setting up $(basename $setup)"
      $setup
      echo ""
      echo "✓"
    fi
  done
fi

"$DOTFILES_ROOT"/script/title "Setup complete."

