#!/bin/sh
#
# Setup stuff. Runs all setups unless given an argument
# Usage is setup [something specific]

target=$1

echo "Starting setup... $target"
if [ ! -z "$target" ]; then
  script/setups/"$target"
else
  for setup in script/setups/*; do
    # Only execute files not directories
    if [ -f "$setup" ]; then $setup; fi
  done
fi
