#!/bin/sh
#
# Setup stuff. Runs all setups unless given an argument
# Usage is setup [something specific]

set -e

# Bootstrap dotfiles if needed
if [[ ! -d "$HOME/.files" ]]; then
  git clone https://github.com/binarymason/dotfiles ~/.files
fi

# Source dotfiles init stuff
source "$HOME/.files/script/init"

# Setup essential things first
"$DOTFILES_ROOT"/script/setups/symlinks

target=${1:-*}
for setup in "$DOTFILES_ROOT"/script/setups/$target; do
  # Only execute files not directories
  if [ -f "$setup" ]; then
    info "Setting up $(basename $setup)"
    $setup
    ok
  fi
done

"$DOTFILES_ROOT"/script/title "Setup complete."

