#!/bin/bash
#
# Update all installed dependencies

set -e

# shellcheck source=lib/globals
source "/$HOME/.files/script/init"

pushd $DOTFILES_ROOT

script/title "Updating Homebrew..."
brew update
brew upgrade

script/title "Updating App Store apps"
mas upgrade

script/title "Updating global Node packages..."
npm update --global
npm upgrade --global

script/title "Updating Ruby"
script/setup/rbenv

script/title "Updating Ruby gems"
gem update --system

script/title "Updating Oh My ZSH"
/bin/sh "$ZSH/tools/upgrade.sh"

popd
