#!/usr/bin/env bash

# Install the Solarized Dark theme for iTerm
# open "${DOTFILES_ROOT}/iterm2/Solarized Dark.itermcolors"

# Don’t display the annoying prompt when quitting iTerm
defaults write com.googlecode.iterm2 PromptOnQuit -bool false

