#!/bin/sh
#
# Installs Dropbox and links Desktop

source "$HOME/.files/script/init"

if [ ! $(brew cask list | grep dropbox) &> /dev/null ]; then
  brew cask install dropbox
fi

if [[ $(readlink "$HOME/Dropbox/Desktop") != "$HOME/Desktop" ]]; then
  # Move everything from existing Dropbox/Desktop to ~/Desktop
  if [ -d "$HOME/Dropbox/Desktop" ] && [ "$(ls -A "$HOME/Dropbox/Desktop")" ]; then
    cp -r "$HOME/Dropbox/Desktop/"* "$HOME/Desktop"
  fi

  # Dropbox folder might not be created until app is opened.
  mkdir_safe "$HOME/Dropbox"

  info "Symlinking Desktop to Dropbox"
  rm -Rf "$HOME/Dropbox/Desktop/"
  ln -s "$HOME/Desktop" "$HOME/Dropbox/Desktop"
fi

echo "Dropbox set."
