#!/bin/sh

# Installs eslint globally with all necessary dependencies.
# Source: https://www.npmjs.com/package/eslint-config-airbnb

source "$HOME/.files/script/init"

if ! command -v eslint > /dev/null; then
  npm install -g eslint
fi

if ! npm list -g eslint-config-airbnb ; then
  PKG=eslint-config-airbnb;
  npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install -g --save-dev "$PKG@latest"
fi
