#!/bin/sh

source "$HOME/.files/script/init"

if [ ! $(brew tap | grep caskroom/fonts) &> /dev/null ]; then
  brew tap "caskroom/fonts"
fi

if [ ! $(brew cask list | grep "font-fira-mono-for-powerline") &> /dev/null ]; then
  echo "installing fira-mono-for-powerline..."
  brew cask install "font-fira-mono-for-powerline"
fi
