#!/bin/sh

source "$HOME/.files/script/init"

if [ ! $(gem list | grep pygments.rb) &> /dev/null ]; then
  gem install pygments.rb
fi

if [ ! command -v ghi &> /dev/null ]; then
  brew install ghi
fi

echo "ghi set."
