#!/bin/sh

source "$HOME/.files/script/init"

brew update
brew doctor

# Install all our dependencies with bundle (See Brewfile)
link_safe $DOTFILES_ROOT/Brewfile
brew tap homebrew/bundle
brew bundle
