#!/bin/sh

source "$HOME/.files/script/init"
echo # newline for asthetics

brew update
brew doctor

# Install all our dependencies with bundle (See Brewfile)
link_safe $DOTFILES_ROOT/Brewfile
brew tap homebrew/bundle
(
 cd "$HOME" || exit
 brew bundle
)

# Remove outdated formulae
brew cleanup
