#!/bin/sh

source "$HOME/.files/script/init"

if ! command -v nvim > /dev/null; then
  echo
  # Changing env to std is hack around lua problems
  brew install neovim/neovim/neovim --env=std
fi

if ! pip3 list --format=columns > /dev/null; then
  echo
  pip3 install neovim
fi

if ! gem list neovim > /dev/null; then
  echo
  gem install neovim
fi

mkdir_safe ~/.config
link_safe $(dot vim) ~/.config/nvim
link_safe $(dot vim/vimrc) ~/.config/nvim/init.vim
