#!/bin/sh

source "$HOME/.files/script/init"

if  [ ! command -v nvim &> /dev/null ] ; then
  # Changing env to std is hack around lua problems
  brew install neovim/neovim/neovim --env=std
fi

mkdir_safe ~/.config
link_safe $(dot vim) ~/.config/nvim
link_safe $(dot vim/vimrc) ~/.config/nvim/init.vim
