#!/bin/sh

source "$HOME/.files/script/init"

${DOTFILES_ROOT}/script/setups/zsh

if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-nvm" &> /dev/null ]; then
  git clone https://github.com/lukechilds/zsh-nvm "$HOME/.oh-my-zsh/custom/plugins/zsh-nvm"
fi

