#!/bin/bash

source "/$HOME/.files/script/init"

OSX_SETUPS=${DOTFILES_ROOT}/osx/*

set -e

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until script has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

for file in $OSX_SETUPS; do
  $file # execute file
done
