#!/bin/sh
#
# Symlinks all dotfiles in DOTFILES_ROOT to home directory

source "$HOME/.files/script/init"

# Create this symlink before linking dotfiles
link_safe $DOTFILES_ROOT/.vim/vimrc $DOTFILES_ROOT/.vimrc

link_dotfiles

link_safe $DOTFILES_ROOT/Brewfile
link_safe $DOTFILES_ROOT/default-gems $(rbenv root)/default-gems

# Dinghy
mkdir_safe $HOME/.dinghy
link_safe $DOTFILES_ROOT/dinghy-preferences.yml $HOME/.dinghy/preferences.yml

mkdir_safe $HOME/Library/LaunchAgents
tmp_reaper_plist="Library/LaunchAgents/com.binarymason.tmpreaper.plist"
link_safe $DOTFILES_ROOT/$tmp_reaper_plist $HOME/$tmp_reaper_plist

update_plist="Library/LaunchAgents/com.binarymason.update.plist"
link_safe $DOTFILES_ROOT/$update_plist $HOME/$update_plist

