#!/bin/sh
#
# Symlinks all dotfiles in DOTFILES_ROOT to home directory

source "/$HOME/.files/script/init"

link_dotfiles

mkdir_safe $HOME/Library/LaunchAgents
tmp_reaper_plist="Library/LaunchAgents/com.binarymason.tmpreaper.plist"
link_safe $DOTFILES_ROOT/$tmp_reaper_plist $HOME/$tmp_reaper_plist

update_plist="Library/LaunchAgents/com.binarymason.update.plist"
link_safe $DOTFILES_ROOT/$update_plist $HOME/$update_plist

