#!/bin/sh

source "$HOME/.files/script/init"

if infocmp $TERM | grep kbs=^[hH] > /dev/null; then
  echo "Fixing Tmux/Neovim/Ctrl-h issue."
  echo "More info here: https://git.io/vKwpo"
  (
    cd $HOME
    infocmp $TERM | sed 's/kbs=^[hH]/kbs=\\177/' > $TERM.ti
    tic $TERM.ti
  )
fi

