#!/bin/sh

TOKEN_PATH=$HOME/.secrets/github-token

mkdir_safe $HOME/.secrets
if [ ! -f "$TOKEN_PATH" ]; then
  echo
  echo "Create a GitHub Personal Access Token with *public* scope"
  echo "by going to https://github.com/settings/tokens"
  echo "and enter it below:"

  if [ "$TRAVIS" != "true" ]; then
    read -r token
  else
    token=""
  fi

  echo "$token" > "$TOKEN_PATH"
  echo "Token saved as $TOKEN_PATH."
fi
