#!/bin/sh

source "$HOME/.files/script/init"

if [ ! command -v brew &> /dev/null ] ; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi


# Universal ctags is HEAD installed and MacOSX ships with a ctags,
# So checking for existing binary doesn't work.  Makes sure brew installed.
if [ ! brew ls --versions universal-ctags &> /dev/null ]; then
  brew tap universal-ctags/universal-ctags
  brew install --HEAD universal-ctags
fi
