#!/bin/sh
#
# source ~/.zshrc
#
# Zsh tab completion is sometimes broken out of the box.
# See http://stackoverflow.com/a/22753363
# if ! compaudit ; then
  # compaudit | xargs chmod g-w
# fi

source "$HOME/.files/script/init"
sameline "(Setup disabled. See file for instructions.)"
