#!/bin/sh

source "/$HOME/.files/script/init"

if [ ! command -v gpg-agent &> /dev/null ]; then
  brew install gpg-agent
fi

# use gpg-agent to store passphrase in OSX keychain
if test -f ~/.gnupg/.gpg-agent-info -a -n "$(pgrep gpg-agent)"; then
  source ~/.gnupg/.gpg-agent-info
  export GPG_AGENT_INFO
else
  eval $(gpg-agent --daemon --write-env-file ~/.gnupg/.gpg-agent-info)
fi

