#!/bin/sh
#
# Setup up rbenv

# shellcheck source=lib/globals
source "$HOME/.files/script/init"

# Install and initialize rbenv
command -v rbenv >/dev/null 2>&1 || { echo >&2 brew install rbenv; eval "$(rbenv init -)"; }

if [ "$(rbenv global)" = "system" ]; then
  if [ ! command -v ruby-build &> /dev/null ]; then
    brew install ruby-build
  fi

  if [ ! rbenv versions | grep "$(latest_ruby)" &> /dev/null ]; then
    echo "Installing latest Ruby version: $(latest_ruby)"
    rbenv install "$(latest_ruby)"
  fi

  rbenv global "$(latest_ruby)"
  rbenv rehash
fi
