#!/bin/sh
#
# Symlinks all dotfiles in DOTFILES_ROOT to home directory

source "/$HOME/.files/script/init"

for file in $(find $DOTFILES_ROOT -name ".[^.]*" -maxdepth 1); do
  if [ $file != $DOTFILES_ROOT ]; then
    link_safe $file
  fi
done

echo "Symlinks set."
