#!/bin/sh
#
# Symlinks all dotfiles in DOTFILES_ROOT to home directory

source "/$HOME/.files/script/init"

for file in $(find $DOTFILES_ROOT -name ".[^.]*" -maxdepth 1); do
  if [ $file != $DOTFILES_ROOT ]; then
    link_safe $file
  fi
done

mkdir_safe $HOME/Library/LaunchAgents
link_safe $DOTFILES_ROOT/Library/LaunchAgents/com.binarymason.tmpreaper.plist
link_safe $DOTFILES_ROOT/Library/LaunchAgents/com.binarymason.update.plist

echo "Symlinks set."
